### ISSUE TITLE
Little confused

### ISSUE THREAD

**Issue by jerryhitit** [Wanggcong/Spatial-Temporal-Re-identification#10]
Hi Bro, I try to utilize your code to prefrom other reid task, and I am little confused by this line. What's the propose of this line?
https://github.com/Wanggcong/Spatial-Temporal-Re-identification/blob/4cdfbd0afd213bb1f43a151b59be18fa16797627/prepare.py#L105

In Market1501, it has two annotations to discribe the camera info, like (person-id)_c(camid)s(recoding sequence id?)_(timestamp)_(count).jpg. 

I think the key means the (seq_id) and the I don't know the exact meaning of the value number.  Dose this value means some kind of video length or the largeset distance between two frames?Am I right? 

Any Help will be appreciated!

**Comment by Wanggcong** [comment]
Video time information on Market1501 contains two parts, i.e., sequence number and frame number. As an simple example, a video contains two sequences, denoted as seq1 ans seq2. Now we have many frames named seq1_frame5, seq1_frame2, seq2_frame11, seq2_frame3, and seq2_frame5. We estimate the length seq1 by compute max{frame5, frame2}=5 and the length seq2 by max{frame11, frame3, frame5}=11. We simply asume this video contains 5+11=16 frames.

Given a frame named seq2_frame2, the frame number of this frame is acturally 
 seq2_frame2=max{frame5, frame2}+frame2=7

Note that this estimation is rough and even not consistent with the real-world scenario, but we do not need such accurate time information. The underlying time pattern exists and thus works.

If you have the more accurate time information, you do not need to compute the time information like this.

I hope this can adddress your question.

**Comment by jerryhitit** [comment]
That help a lot!

**Comment by zhangp14** [comment]
> 
> 
> Video time information on Market1501 contains two parts, i.e., sequence number and frame number. As an simple example, a video contains two sequences, denoted as seq1 ans seq2. Now we have many frames named seq1_frame5, seq1_frame2, seq2_frame11, seq2_frame3, and seq2_frame5. We estimate the length seq1 by compute max{frame5, frame2}=5 and the length seq2 by max{frame11, frame3, frame5}=11. We simply asume this video contains 5+11=16 frames.
> 
> Given a frame named seq2_frame2, the frame number of this frame is acturally
> seq2_frame2=max{frame5, frame2}+frame2=7
> 
> Note that this estimation is rough and even not consistent with the real-world scenario, but we do not need such accurate time information. The underlying time pattern exists and thus works.
> 
> If you have the more accurate time information, you do not need to compute the time information like this.
> 
> I hope this can adddress your question.

But you can not make sure the maximum value of seq1_frame5 is the total length of seq1.
It is possible, after frame5, there is a long time gap that no person will appears before seq2 start.
But, according to your assumption, the time stamp of seq2_frame1 will be 5+1=6. That doesn't make sense.
I am wondering, if the length information of each seq in each camera is lacking, how could you calculate the travel time between any two camera correctly?

I am not sure, in the conference paper, you draw Spatial-temporal distribution (Fig.2 and Fig.3) using DukeMTMC-reID dataset instead of Market-1501. just because video information of Market-1501 is lacking.?

**Comment by Wanggcong** [comment]
Q1: But you can not make sure the maximum value of seq1_frame5 is the total length of seq1.
A1:Yep, this is why I say "Note that this estimation is rough and even not consistent with the real-world scenario, but we do not need such accurate time information. The underlying time pattern exists and thus works."

Commonly, in video monitoring systems, videos are automatically split into several clips with varying lengths (if you have collected such a dataset, you would know this). But actually we do not know the details about the data collection. As mentioned above, even though this estimation is rough, some underlying spatial-temporal patterns exist and the smoothing operator could alleviate the inaccurate estimation and brings an improvement.

If you have the more accurate info, I think it could further improve the performance.

Q2: Using DukeMTMC-reID dataset instead of Market-1501 for drawing Figs. 2&3?
A2: The market dataset is originally collected for person retrieval, not person re-id. It exists overlapping camera views. In the standard person reid setting, there is no overlap between different camera views. In the market dataset, a person could be simultaneously captured by two cameras, which is somewhat messy to visualize the spatial-temporal distribution. From my own opinion, market is for person retrieval (although it is widely used for reid in many works), but not a standard dataset for non-overlapping person reid, which could be more useful for real-world scenarios.

I draw figs. 2&3 using the duke dataset because there is no overlap between different cameras and duke is collected from a more complex scenario, which could be more like to real-world scenes, not because of the inaccurate time info.
